export interface Subject {
  id: string
  name: string
  color: string
  lessonCount: number
  nextExam: string | null
  icon: string
}

export interface Lesson {
  id: string
  subjectId: string
  topicId?: string
  date: string
  topic: string
  duration: number
  hasNotes: boolean
}

export interface HalfYear {
  id: string
  name: string
  period: string
  isCurrent: boolean
}

export interface Topic {
  id: string
  subjectId: string
  halfYearId: string
  name: string
  kcAligned: boolean
  lessonIds: string[]
}

export interface SmartNote {
  id: string
  lessonId: string
  summary: string
  keywords: string[]
  examTopics: string[]
}

export interface FlashCard {
  id: string
  subjectId: string
  front: string
  back: string
}

export interface ExamQuestion {
  id: string
  subjectId: string
  text: string
  points: number
  operator: string
}

export interface ExamResult {
  questionId: string
  userAnswer: string
  score: number
  maxScore: number
  grade: string
  strengths: string[]
  weaknesses: string[]
  suggestion: string
}

export interface UserFolder {
  id: string
  subjectId: string
  halfYearId?: string
  parentFolderId?: string
  name: string
  createdAt: string
  isAutoGenerated?: boolean
}

export interface UserNote {
  id: string
  subjectId?: string
  folderId?: string
  title: string
  content: string
  attachments?: string[]
  qa?: { q: string; a: string }[]
  createdAt: string
}

export interface StundenplanSlot {
  id: string
  day: number // 0=Mo, 1=Di, 2=Mi, 3=Do, 4=Fr
  startTime: string // "08:00"
  endTime: string   // "08:45"
  subjectId: string
  room?: string
}

export interface Stundenplan {
  slots: StundenplanSlot[]
  createdAt: string
}

export interface GeneratedSmartNote {
  lessonId: string
  rawText: string
  contentType?: 'info' | 'aufgabe' | 'beides'
  summary: string
  keywords: string[]
  examTopics: string[]
  solution?: { steps: string[]; answer: string; proof?: string }
  tasks?: Array<{ question: string; steps: string[]; answer: string; proof?: string }>
  generatedAt: string
  subjectName: string
}
